# Generated by Django 4.0.6 on 2022-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100)),
                ('qr_image', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('qr_url', models.URLField()),
                ('qr_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'QR Code Generation',
            },
        ),
    ]
