# Generated by Django 4.0.6 on 2022-07-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_easy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrGen',
        ),
    ]
